import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/app/(Root)/globals.css"
import { Providers } from "./../providers"
import { Session } from "inspector"
import { SessionProvider } from "next-auth/react"
import { auth } from "@/lib/auth"
import { redirect } from "next/navigation"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Providers>{children}</Providers>
        </SessionProvider>
      </body>
    </html>
  )
}
