import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/app/(Root)/globals.css"
import { Providers } from "./../providers"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"

const inter = Inter({ subsets: ["latin"] })
import { ViewTransitions } from "next-view-transitions"

import { AppNav } from "./(components)/appnav"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={inter.className + " dark"}>
          <Providers>
            <div className="max-w-7xl h-screen mx-auto">
              <AppNav />
              {children}
            </div>
          </Providers>
        </body>
      </html>
    </ViewTransitions>
  )
}
